### ISSUE TITLE
Hangs on Windows

### ISSUE THREAD

**Issue by juntalis** [dejw/vip#1]
Hey,

Noticed an issue where trying to initialize a new vip environment on Windows would result in the script hanging forever. It appears to be caused by [line 59 in the vip/core.py](https://github.com/dejw/vip/blob/master/vip/core.py#L59) file. Making the following change to that line seems to make it work fine on Windows.

```
    while directory != "/" or head:
```

to

```
    while (directory != "/" and directory[1:] != ':\\' and directory[1:] != ':/') or head:
```

Was debating forking and doing a pull request, but I figured this would be easier.

**Comment by dejw** [comment]
Thanks for creating the ticket. In fact I did not thought initially this tool might be used on Windows, and that is why it was not tested under such OS.

Will try to incorporate your fix as soon as I can, but in fact you can create a pull request if you would like to. Otherwise I need to setup a brand new development environment on my Windows, which may take some time.

**Comment by juntalis** [comment]
Sure thing, I'll go ahead and throw something together.
